name: Code style

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install package and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]

      - name: Lint with flake8
        run: flake8 hcvote

      - name: Check style with black
        run: black hcvote --check

      - name: Check imports with isort
        run: isort hcvote --check-only

      - name: Type check with mypy
        run: mypy hcvote
