name: Unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: Install package and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[test]

      - name: Run unit tests
        run: |
          pytest --cov=hcvote --cov-report=xml

      - name: Upload coverage report to codecov.io
        uses: codecov/codecov-action@v3
